-- DROP DATABASE IF EXISTS nyc_covid;
-- CREATE DATABASE nyc_covid;

-- DROP USER IF EXISTS nyc_covid;
-- CREATE USER nyc_covid WITH PASSWORD 'nyc_covid';

-- GRANT ALL PRIVILEGES ON DATABASE nyc_covid TO nyc_covid;

--DROP SCHEMA IF EXISTS testing CASCADE;
--CREATE SCHEMA testing;
--ALTER USER nyc_covid SET search_path = testing;
--GRANT ALL PRIVILEGES ON SCHEMA testing TO nyc_covid;

-- DROP TABLE IF EXISTS nursing_home_quality;

-- DROP TABLE IF EXISTS facility;

-- DROP TABLE IF EXISTS measurment;

-- DROP TABLE IF EXISTS users;

-- DROP DATABASE IF EXISTS nyc_covid;

-- DROP SCHEMA IF EXISTS testing CASCADE;

-- DROP USER IF EXISTS nyc_covid;

-- CREATE DATABASE nyc_covid;
-- CREATE USER nyc_covid WITH PASSWORD 'nyc_covid';
-- GRANT ALL PRIVILEGES ON DATABASE nyc_covid TO nyc_covid;


-- CREATE SCHEMA testing;
-- ALTER USER admin SET search_path = testing;
-- GRANT ALL PRIVILEGES ON SCHEMA testing TO nyc_covid;

CREATE TABLE counties (
    ID INT PRIMARY KEY,
    DATE DATE,
    GEOID CHAR(9),
    COUNTY VARCHAR(60),
    STATE VARCHAR(60),
    CASES INT,
    CASES_AVG FLOAT,
    CASES_AVG_PER_100K FLOAT,
    DEATHS INT,
    DEATHS_AVG FLOAT,
    DEATHS_AVG_PER_100K FLOAT
    );

CREATE TABLE hospital_data (
    NAME VARCHAR(127),
    ALT_NAME VARCHAR(127),
    OBJECTID INT UNIQUE,
    ID BIGINT PRIMARY KEY,
    STATUS VARCHAR(10),
    TYPE VARCHAR(127),
    TRAUMA	VARCHAR(64),
    OWNER VARCHAR(32),
    TTL_STAFF INT,	
    POPULATION INT,
    BEDS INT,	
    HELIPAD	CHAR,
    NAICS_CODE INT,
    NAICS_DESC VARCHAR(127)
);

CREATE TABLE metadata(
    OBJECTID INT REFERENCES hospital_data (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES hospital_data (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    SOURCE	VARCHAR(256),
    SOURCEDATE TIMESTAMP,
    VAL_METHOD	VARCHAR(127),
    VAL_DATE TIMESTAMP
);

Create table contact_data(
    OBJECTID INT REFERENCES hospital_data (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID BIGINT REFERENCES hospital_data (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    TELEPHONE VARCHAR(15),	
    WEBSITE VARCHAR(256)
);

CREATE TABLE address_data(
    OBJECTID INT REFERENCES hospital_data (OBJECTID) ON UPDATE CASCADE ON DELETE CASCADE,    
    ID BIGINT REFERENCES hospital_data (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    X DECIMAL(12,4),	
    Y DECIMAL(12,4),	
    ADDRESS	VARCHAR(127),
    CITY VARCHAR(30),	
    COUNTY VARCHAR(20),	
    COUNTYFIPS INT,
    STATE CHAR(2),
    STATE_ID VARCHAR(20),	
    ST_FIPS	INT,
    ZIP	INT,
    COUNTRY	CHAR(3) DEFAULT 'USA',
    LATITUDE DECIMAL(10,4),
    LONGITUDE DECIMAL(11,4)
);

CREATE TABLE user_data(
    user_name VARCHAR(50) PRIMARY KEY,
    login_count INT
);
CREATE TABLE user_activity_log(
    user_name VARCHAR(50) REFERENCES user_data(user_name) ON UPDATE CASCADE ON DELETE CASCADE,
    query_run INT,
    tables_accessed VARCHAR(50),
    login_count INT
)

